image: ayufan/rock64-dockerfiles:bookworm

variables:
  GITHUB_USER: ayufan-rock64
  GITHUB_REPO: linux-package

stages: [build]

build:
  stage: build
  only: [branches]
  script:
    - export RELEASE="$CI_PIPELINE_IID"
    - chmod go-w -R . # fix umask, as GitLab CI uses 0000
    - make BOARD_TARGET=rock64
    - make BOARD_TARGET=rockpro64
    - make BOARD_TARGET=rockpi4b
    - make BOARD_TARGET=rockpi5b
    - make BOARD_TARGET=pinebookpro
    - |
      set -x

      export RELEASE_NAME="$(make version BOARD_TARGET=rock64)"
      export RELEASE_TITLE="$(make release BOARD_TARGET=rock64)"
      export DESCRIPTION="$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID"

      github-release release \
        --tag "${RELEASE_NAME}" \
        --name "${RELEASE_TITLE}" \
        --description "${DESCRIPTION}" \
        --target "${CI_COMMIT_SHA}" \
        --draft

      for i in *.deb; do
        github-release upload \
          --tag "${RELEASE_NAME}" \
          --name "${i}" \
          --file "${i}"
      done

      github-release edit \
        --tag "${RELEASE_NAME}" \
        --name "${RELEASE_TITLE}" \
        --description "${DESCRIPTION}"
