#!/bin/bash

if [[ $# -ne 0 ]] && [[ $# -ne 1 ]]; then
  echo "usage: $0 [kernel-version]"
  exit 1
fi

VERSION=${VERSION:-$(uname -r)}

set -xe
pushd /boot

if [[ ! -e "dts-${VERSION}" ]]; then
  if [[ "$VERSION" == "$(uname -r)" ]]; then
    dtc "/sys/firmware/fdt" > "dts-${VERSION}.tmp"
  else
    dtc "dtb-${VERSION}" > "dts-${VERSION}.tmp"
  fi
  mv "dts-${VERSION}.tmp" "dts-${VERSION}"
fi

editor "dts-${VERSION}"

dtc "dts-${VERSION}" > "dtb-${VERSION}.new"
mv "dtb-${VERSION}.new" "dtb-${VERSION}"
update_extlinux.sh
echo Done.
