on: [push]

env:
  RELEASE_START: 213
  CCACHE_DIR: $RUNNER_TEMP/ccache

jobs:
  build:
    # runs-on: [self-hosted, Linux, ARM64]
    runs-on: ubuntu-latest
    container: ayufan/rock64-dockerfiles:bookworm
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure version
      run: echo "RELEASE=$(($RELEASE_START+$GITHUB_RUN_NUMBER))" >> $GITHUB_ENV
    - name: Cleanup old packages
      run: rm -f *.deb
    - name: Build packages
      run: make all-boards
    - name: Release package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x

        export RELEASE_NAME="$(make version BOARD_TARGET=rock64)"
        export RELEASE_TITLE="$(make version BOARD_TARGET=rock64)"
        export DESCRIPTION="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

        github-release release \
          --tag "${RELEASE_NAME}" \
          --name "${RELEASE_TITLE}" \
          --user "${GITHUB_REPOSITORY%/*}" \
          --repo "${GITHUB_REPOSITORY#*/}" \
          --description "${DESCRIPTION}" \
          --target "${GITHUB_SHA}" \
          --draft

        sleep 3s # allow to update release

        for i in *.deb; do
          github-release upload \
            --tag "${RELEASE_NAME}" \
            --name "$(basename "${i}")" \
            --user "${GITHUB_REPOSITORY%/*}" \
            --repo "${GITHUB_REPOSITORY#*/}" \
            --file "${i}"
        done

        github-release edit \
          --tag "${RELEASE_NAME}" \
          --name "${RELEASE_TITLE}" \
          --user "${GITHUB_REPOSITORY%/*}" \
          --repo "${GITHUB_REPOSITORY#*/}" \
          --description "${DESCRIPTION}"
